openapi: '3.0.2'
info:
  title: AICCELERATE Multi-Model Predictions API
  version: '1.0.1'
  description: 'Predictions API for Pilot 1.1 (HSJD) in the AICCELERATE project.'
servers:
  - url: https://TBA/v1
paths:
  /ping:
    get:
      description: 'Health check of gateway'
      responses:
        '200':
          description: OK
  /list:
    get:
      description: "Returns a list of the models hosted on the server."
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: 
                   $ref: "AICCELERATE_Api_Definitions.yml#/definitions/schemas/ModelInfoResponse"
                  
  /model/{modelName}:
    post:
      description: "Invokes the model for the given patient id and returns the result"
      parameters:
        - in: path
          name: modelName
          schema:
            type: string
          required: true
          description: name of the model
      requestBody:
        content:
          application/json:
            schema:
              $ref: "AICCELERATE_Api_Definitions.yml#/definitions/schemas/InferenceRequest"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  inference:
                    $ref: "AICCELERATE_Api_Definitions.yml#/definitions/schemas/ModelInferenceResponse"
                  explanation: 
                    $ref: "AICCELERATE_Api_Definitions.yml#/definitions/schemas/ModelXAIResponse"
    get:
      description: 'Retrieve information about the model'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'AICCELERATE_Api_Definitions.yml#/definitions/schemas/ModelInfoResponse'
  /model/{modelName}/ping:
    get:
      description: 'Health check of model'
      responses:
        '200':
          description: OK